name: sui_sec_blocklist
description: "Fetch and execute lookups on Suiet Guardians blocklists"
version: 0.1.0
homepage: https://github.com/SurfWallet/sui_sec_blocklist

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  http: ^1.2.2
  html: ^0.15.4
#  web: ^1.1.0

dev_dependencies:
  test: ^1.25.7
  lints: ^4.0.0