name: sui_sec_blocklist
description: Fetch and execute lookups on Suiet Guardians blocklists. Protect your wallet from phishing.
homepage: https://github.com/SurfWallet/sui_sec_blocklist
issue_tracker: https://github.com/SurfWallet/sui_sec_blocklist/issues
version: 0.1.11

environment:
  sdk: '>=3.3.4 <4.0.0'

topics:
  - sui

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  html: ^0.15.4
  path_provider: ^2.1.2
  path: ^1.9.0
#  web: ^1.1.0

dev_dependencies:
  lints: ^4.0.0